# Read more about feature here TBD
#
# Tool can be configured using environment variable but as of now only one tool is configured

sast:
#  stage: test
#  image: docker:stable
#  variables:
#    XYZ: xyz
  allow_failure: true
  script:
      docker run -v /$(pwd):/src opensecurity/nodejsscan:cli -d /src -o /src/results.json
  artifacts:
    reports:
      sast: gl-sast-report.json
  dependencies: []
  only:
    refs:
      - branches
    variables:
      - $FEATURES =~ /\bsast\b/
  except:
    variables:
      - $SAST_DISABLED
